# -*- coding: utf-8 -*-
"""AI_Powered_Demand_Forecasting_&_Knowledge_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBDGdaZV_wIWynlEdxuwEvvS9dqbhARc

#***AI-Powered Demand Forecasting & Knowledge Assistant***

**Problem Statement**

**To develop an intelligent AI system that predicts demand for electronic products and answers user queries using machine learning, retrieval-based search (RAG), and large language models.**

Businesses often struggle to accurately predict product demand and analyze large datasets manually. This project aims to develop an Agentic AI system that automates demand prediction for electronic devices using features like price, rating, brand, and location, while also enabling intelligent query answering by retrieving relevant data through embeddings and generating responses using a large language model.

**Objectives**
- Predict product demand using ML model
- Process and clean real-world dataset
- Convert text data into embeddings
- Build FAISS-based search system
- Generate answers using LLM (Gemini)
- Implement decision agent for smart routing
- Create chatbot interface for user interaction

#**1. Imports**
"""

# Core
import pandas as pd
import numpy as np

# ML
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Embeddings + Vector DB
from sentence_transformers import SentenceTransformer
!pip install faiss-cpu
!pip install sentence-transformers
import faiss

# Gemini (ONLY THIS)
from google import genai
from google.colab import userdata

"""**🔹Core Libraries**

pandas (pd) → handle dataset (table format)

numpy (np) → perform numerical calculations

**🔹 Machine Learning**

train_test_split → divide data (train + test)

StandardScaler → scale data (same range)

RandomForestRegressor → predict demand using multiple trees

mean_absolute_error (MAE) → check prediction accuracy


**🔹 Embeddings + FAISS**

SentenceTransformer → convert text → numerical vectors

faiss → fast similarity search (find related data)


**🔹 Installation**

pip install → installs required libraries

**🔹 Gemini AI**

genai → connect to Gemini model (AI responses)

userdata → safely store API key

#**2. Gemini Setup**

We fetch API key securely and initialize Gemini client for AI communication.👍
"""

API_KEY = userdata.get('GOOGLE_API_KEY')
client = genai.Client(api_key=API_KEY)

"""#**3. Data Preprocessing**

Load dataset, clean missing & duplicate data, encode categorical features, split into input/output, and scale features for ML model training. 👍
"""

df = pd.read_csv("/content/drive/MyDrive/Agentic AI/electronic_device_data.csv")

# Drop unwanted
df.drop(columns=['Source_File', 'Source_Demand_Level'], errors='ignore', inplace=True)

# Fill missing
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Remove duplicates
df.drop_duplicates(inplace=True)

# One-hot encoding (ONLY THIS)
df = pd.get_dummies(df, drop_first=True)

# Split
target_column = 'Demand_Score'
X = df.drop(columns=[target_column])
y = df[target_column]

# Scale
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

"""#**4. Train Model**

Split data into training and testing, train Random Forest model, make predictions, and evaluate accuracy using MAE. 👍
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, preds))

"""#**5. Prediction Function**

Convert user input to model format, match all features, scale it, and use trained model to predict demand. 👍
"""

def predict_demand(input_dict):
    input_df = pd.DataFrame([input_dict])

    # Ensure all columns exist
    for col in X.columns:
        if col not in input_df:
            input_df[col] = 0

    input_df = input_df[X.columns]

    scaled = scaler.transform(input_df)
    return model.predict(scaled)[0]

"""#**6. Embedding + FAISS**

Create text embeddings from dataset and store them in FAISS index for fast similarity-based retrieval. 👍
"""

from google.colab import userdata
import os
from huggingface_hub import login

os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

df['text'] = df.astype(str).agg(" ".join, axis=1)
documents = df['text'].tolist()

embeddings = embedding_model.encode(documents)
embeddings = np.array(embeddings).astype('float32')

index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)

"""#**7. Retrieval**

Convert user query into embedding, search FAISS index, and return top similar documents. 👍
"""

def retrieve_docs(query, top_k=10):
    query_vec = embedding_model.encode([query])
    D, I = index.search(np.array(query_vec).astype('float32'), top_k)
    return [documents[i] for i in I[0]]

"""#**8. LLM Response**"""

def llm_response(prompt):
    response = client.models.generate_content(
        model="gemini-flash-latest", # Changed to gemini-flash-latest
        contents=prompt
    )
    return response.text

for m in client.models.list():
    print(m.name)

"""#**9. RAG Agent**"""

def rag_agent(query):
    docs = retrieve_docs(query)
    context = "\n".join(docs)

    prompt = f"""
Use this data:

{context}

Answer:
{query}
"""

    return llm_response(prompt)

"""#**10. NLP → Prediction Agent**

Use LLM to extract structured features from query in JSON format and return them for prediction. 👍
"""

import json

def extract_features(query):
    prompt = f"""
Extract features as JSON.

Query: {query}
"""
    res = llm_response(prompt)

    try:
        return json.loads(res)
    except:
        return {}

"""Extract features from query, convert to model input format, and predict demand using the trained model. 👍"""

def prediction_agent(query):
    data = extract_features(query)

    input_dict = {col: 0 for col in X.columns}

    for k, v in data.items():
        if k in input_dict:
            input_dict[k] = v
        else:
            col_name = f"{k}_{v}"
            if col_name in input_dict:
                input_dict[col_name] = 1

    demand = predict_demand(input_dict)

    return f"Predicted Demand: {demand}"

"""#**11. Decision Agent**

Check user query and decide whether to use prediction model or RAG-based answer system. 👍
"""

def decision_agent(query):
    if "predict" in query.lower() or "forecast" in query.lower():
        return prediction_agent(query)
    else:
        return rag_agent(query)

"""#**12. Chatbot**

Continuously take user input, process it using decision agent, and display the chatbot response until exit. 👍
"""

def chatbot():
    while True:
        q = input("You: ")
        if q == "exit":
            break
        print("Bot:", decision_agent(q))

chatbot()

